### ISSUE TITLE
onActivityResult gets invoked from other module

### ISSUE THREAD

**Issue by saikiranvadlakonda** [JoaoCnh/react-native-android-voice#9] opened 2016-05-12 09:41 UTC
Hi,
I'm developing android app using react-native. In that I'm using current module for speech to text and to capture image or upload image I'm using [ImagePickerManager](https://github.com/marcshilling/react-native-image-picker), If I use them individually they are working fine, but if I integrate them then image capturing is not working and app gets crashed. I've enabled log and seen that after capturing or selecting an image this module was called, don't know why this module onActivityResult is called android should call image picker manager's onActivityResult. May be I'm thinking that, Is there any code that makes android to call only this modules onActivityResult. Could you tell me why It's getting invoking from other module.
Below is the error log image.
![screenshot from 2016-05-12 15 11 04](https://cloud.githubusercontent.com/assets/14762284/15387561/693b90ae-1dcb-11e6-9657-78249bfb6e3c.png)

**Comment by JoaoCnh** [comment] 2016-05-19 08:25
@saikiranvadlakonda Sorry for the delay. But your linked image is not working.

I'll try to figure out what the problem is. Surely it shouldn't be happening.

**Comment by narongdejsrn** [comment] 2016-05-31 11:09
I also get this problem too, but from react-native-facebook-login plugin

**Comment by saikiranvadlakonda** [comment] 2016-05-31 11:19
After doing some R&D, I find out that there is no null handling code in [onActivityResult()](https://github.com/JoaoCnh/react-native-android-voice/blob/master/src/main/java/com/wmjmc/reactspeech/VoiceModule.java#L73) method, add 

```
if(data!=null && mVoicepromise!=null){
switch (resultCode){
....
}
```

Hope this will save you from getting exception.

**Comment by JoaoCnh** [comment] 2016-05-31 11:22
@saikiranvadlakonda @zenyai I have actually a pull request for this already.

I have merged and I have published the npm update.
Any feedback feel free to re-open the issue.

**Closed as completed** 2016-05-31 11:33 UTC
